In [38]:
# importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# display aesthetics
from IPython.display import display
%matplotlib inline
pd.set_option('display.max_columns', 55)
pd.options.display.float_format = '{:.5f}'.format

import warnings
warnings.filterwarnings('ignore')

In [40]:
# load the dataset
data = pd.read_csv('data.csv')
data.head()

,Applicant_ID,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field23,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field31,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50,default_status,set
0,Apcnt_1000000,3436.00000,0.28505,1.65600,0.00000,0.00000,0.00000,10689720.00000,252072.00000,4272776.00000,11333126.00000,4397256.00000,2301324.00000,7875694.00000,96375139,112181765.00000,1.00000,1.00000,1.00000,3.00000,3.00000,134.65500,nan,nan,134.65500,4000.50000,17064.00000,11376.00000,60.00000,17064.00000,5962.00000,nan,1052.00000,8.00000,2.00000,nan,12.00000,12.00000,4.00000,0.00000,nan,nan,0.39285,2.02000,0.71163,0.00000,0.00000,charge,nan,1.12952,0.04433,0.00000,train
1,Apcnt_1000004,3456.00000,0.67400,0.23420,0.00000,0.00000,0.00000,898979.00000,497531.00000,9073814.00000,2533168.00000,244292.00000,3982971.00000,2141445.00000,28141427,45169902.00000,1.00000,1.00000,1.00000,2.00000,2.00000,109.23000,11385.24000,14584.29000,86.68500,4161.00000,13413.00000,8942.00000,304.00000,13413.00000,5780.00000,nan,2554.00000,17.50000,0.00000,0.00000,16.00000,24.00000,8.00000,0.00000,nan,nan,0.31428,8.08000,0.18358,nan,0.00000,charge,349.80573,1.62048,0.32244,0.00000,train
2,Apcnt_1000008,3276.00000,0.53845,3.15100,0.00000,6.28200,nan,956940.00000,nan,192944.00000,1079864.00000,nan,nan,0.00000,16576457,22452691.00000,nan,nan,nan,0.00000,0.00000,nan,nan,nan,nan,1597.50000,4746.00000,3164.00000,60.00000,15696.00000,nan,14508.00000,70.00000,0.66660,0.00000,nan,12.00000,0.00000,6.00000,0.00000,149.68050,nan,0.16297,18.18000,0.79114,0.00000,0.00000,charge,nan,1.51337,0.01164,1.00000,train
3,Apcnt_1000012,3372.00000,0.17005,0.50500,0.00000,0.00000,192166.00000,3044703.00000,385499.00000,3986472.00000,3621979.00000,nan,771776.00000,1186839.00000,48187375,136297820.00000,0.00000,0.00000,0.00000,1.00000,1.00000,120.12000,8580.00000,0.00000,85.80000,1701.00000,4014.00000,2676.00000,60.00000,11679.00000,nan,nan,522.00000,7.83340,1.00000,1.00000,4.00000,8.00000,4.00000,1.00000,nan,nan,0.48888,2.02000,0.68517,nan,0.00000,charge,89.94010,0.66445,0.08273,0.00000,train
4,Apcnt_1000016,3370.00000,0.77270,1.10100,0.00000,0.00000,1556.00000,214728.00000,214728.00000,1284089.00000,361770.00000,396391.00000,818456.00000,511535.00000,28141427,15292757.00000,0.00000,0.00000,0.00000,3.00000,3.00000,104.53500,8360.19000,10326.45000,115.33500,1551.00000,3285.00000,2190.00000,60.00000,19437.00000,12958.00000,5202.00000,272.00000,1.00000,0.00000,0.00000,24.00000,2.00000,24.00000,0.00000,150.01350,nan,0.27500,12.12000,0.43817,0.00000,0.00000,charge,97.88750,1.42789,0.04563,0.00000,train

In [41]:
# drop variables with more than 50% missing values

cols = ['form_field40','form_field31','form_field41','form_field45','form_field11','form_field23']

data.drop(columns=cols, axis=1, inplace=True)
data.head()

,Applicant_ID,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field42,form_field43,form_field44,form_field46,form_field47,form_field48,form_field49,form_field50,default_status,set
0,Apcnt_1000000,3436.00000,0.28505,1.65600,0.00000,0.00000,0.00000,10689720.00000,252072.00000,4272776.00000,11333126.00000,2301324.00000,7875694.00000,96375139,112181765.00000,1.00000,1.00000,1.00000,3.00000,3.00000,134.65500,nan,134.65500,4000.50000,17064.00000,11376.00000,60.00000,17064.00000,5962.00000,1052.00000,8.00000,2.00000,nan,12.00000,12.00000,4.00000,0.00000,0.39285,2.02000,0.71163,0.00000,charge,nan,1.12952,0.04433,0.00000,train
1,Apcnt_1000004,3456.00000,0.67400,0.23420,0.00000,0.00000,0.00000,898979.00000,497531.00000,9073814.00000,2533168.00000,3982971.00000,2141445.00000,28141427,45169902.00000,1.00000,1.00000,1.00000,2.00000,2.00000,109.23000,11385.24000,86.68500,4161.00000,13413.00000,8942.00000,304.00000,13413.00000,5780.00000,2554.00000,17.50000,0.00000,0.00000,16.00000,24.00000,8.00000,0.00000,0.31428,8.08000,0.18358,0.00000,charge,349.80573,1.62048,0.32244,0.00000,train
2,Apcnt_1000008,3276.00000,0.53845,3.15100,0.00000,6.28200,nan,956940.00000,nan,192944.00000,1079864.00000,nan,0.00000,16576457,22452691.00000,nan,nan,nan,0.00000,0.00000,nan,nan,nan,1597.50000,4746.00000,3164.00000,60.00000,15696.00000,nan,70.00000,0.66660,0.00000,nan,12.00000,0.00000,6.00000,0.00000,0.16297,18.18000,0.79114,0.00000,charge,nan,1.51337,0.01164,1.00000,train
3,Apcnt_1000012,3372.00000,0.17005,0.50500,0.00000,0.00000,192166.00000,3044703.00000,385499.00000,3986472.00000,3621979.00000,771776.00000,1186839.00000,48187375,136297820.00000,0.00000,0.00000,0.00000,1.00000,1.00000,120.12000,8580.00000,85.80000,1701.00000,4014.00000,2676.00000,60.00000,11679.00000,nan,522.00000,7.83340,1.00000,1.00000,4.00000,8.00000,4.00000,1.00000,0.48888,2.02000,0.68517,0.00000,charge,89.94010,0.66445,0.08273,0.00000,train
4,Apcnt_1000016,3370.00000,0.77270,1.10100,0.00000,0.00000,1556.00000,214728.00000,214728.00000,1284089.00000,361770.00000,818456.00000,511535.00000,28141427,15292757.00000,0.00000,0.00000,0.00000,3.00000,3.00000,104.53500,8360.19000,115.33500,1551.00000,3285.00000,2190.00000,60.00000,19437.00000,12958.00000,272.00000,1.00000,0.00000,0.00000,24.00000,2.00000,24.00000,0.00000,0.27500,12.12000,0.43817,0.00000,charge,97.88750,1.42789,0.04563,0.00000,train

In [42]:
# Handling Categorical variables
data = pd.get_dummies(data, columns = ['form_field47'])
data.head()

,Applicant_ID,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field42,form_field43,form_field44,form_field46,form_field48,form_field49,form_field50,default_status,set,form_field47_charge,form_field47_lending
0,Apcnt_1000000,3436.00000,0.28505,1.65600,0.00000,0.00000,0.00000,10689720.00000,252072.00000,4272776.00000,11333126.00000,2301324.00000,7875694.00000,96375139,112181765.00000,1.00000,1.00000,1.00000,3.00000,3.00000,134.65500,nan,134.65500,4000.50000,17064.00000,11376.00000,60.00000,17064.00000,5962.00000,1052.00000,8.00000,2.00000,nan,12.00000,12.00000,4.00000,0.00000,0.39285,2.02000,0.71163,0.00000,nan,1.12952,0.04433,0.00000,train,1,0
1,Apcnt_1000004,3456.00000,0.67400,0.23420,0.00000,0.00000,0.00000,898979.00000,497531.00000,9073814.00000,2533168.00000,3982971.00000,2141445.00000,28141427,45169902.00000,1.00000,1.00000,1.00000,2.00000,2.00000,109.23000,11385.24000,86.68500,4161.00000,13413.00000,8942.00000,304.00000,13413.00000,5780.00000,2554.00000,17.50000,0.00000,0.00000,16.00000,24.00000,8.00000,0.00000,0.31428,8.08000,0.18358,0.00000,349.80573,1.62048,0.32244,0.00000,train,1,0
2,Apcnt_1000008,3276.00000,0.53845,3.15100,0.00000,6.28200,nan,956940.00000,nan,192944.00000,1079864.00000,nan,0.00000,16576457,22452691.00000,nan,nan,nan,0.00000,0.00000,nan,nan,nan,1597.50000,4746.00000,3164.00000,60.00000,15696.00000,nan,70.00000,0.66660,0.00000,nan,12.00000,0.00000,6.00000,0.00000,0.16297,18.18000,0.79114,0.00000,nan,1.51337,0.01164,1.00000,train,1,0
3,Apcnt_1000012,3372.00000,0.17005,0.50500,0.00000,0.00000,192166.00000,3044703.00000,385499.00000,3986472.00000,3621979.00000,771776.00000,1186839.00000,48187375,136297820.00000,0.00000,0.00000,0.00000,1.00000,1.00000,120.12000,8580.00000,85.80000,1701.00000,4014.00000,2676.00000,60.00000,11679.00000,nan,522.00000,7.83340,1.00000,1.00000,4.00000,8.00000,4.00000,1.00000,0.48888,2.02000,0.68517,0.00000,89.94010,0.66445,0.08273,0.00000,train,1,0
4,Apcnt_1000016,3370.00000,0.77270,1.10100,0.00000,0.00000,1556.00000,214728.00000,214728.00000,1284089.00000,361770.00000,818456.00000,511535.00000,28141427,15292757.00000,0.00000,0.00000,0.00000,3.00000,3.00000,104.53500,8360.19000,115.33500,1551.00000,3285.00000,2190.00000,60.00000,19437.00000,12958.00000,272.00000,1.00000,0.00000,0.00000,24.00000,2.00000,24.00000,0.00000,0.27500,12.12000,0.43817,0.00000,97.88750,1.42789,0.04563,0.00000,train,1,0

In [43]:
# drop applicant ID column

data.drop(columns = 'Applicant_ID', inplace=True, axis=1)

In [44]:
data.columns

Index(['form_field1', 'form_field2', 'form_field3', 'form_field4',
       'form_field5', 'form_field6', 'form_field7', 'form_field8',
       'form_field9', 'form_field10', 'form_field12', 'form_field13',
       'form_field14', 'form_field15', 'form_field16', 'form_field17',
       'form_field18', 'form_field19', 'form_field20', 'form_field21',
       'form_field22', 'form_field24', 'form_field25', 'form_field26',
       'form_field27', 'form_field28', 'form_field29', 'form_field30',
       'form_field32', 'form_field33', 'form_field34', 'form_field35',
       'form_field36', 'form_field37', 'form_field38', 'form_field39',
       'form_field42', 'form_field43', 'form_field44', 'form_field46',
       'form_field48', 'form_field49', 'form_field50', 'default_status', 'set',
       'form_field47_charge', 'form_field47_lending'],
      dtype='object')

In [45]:
# impute missing values using mean

miss_cols = ['form_field1', 'form_field2', 'form_field3', 'form_field4',
       'form_field5', 'form_field6', 'form_field7', 'form_field8',
       'form_field9', 'form_field10', 'form_field12', 'form_field13',
       'form_field14', 'form_field15', 'form_field16', 'form_field17',
       'form_field18', 'form_field19', 'form_field20', 'form_field21',
       'form_field22', 'form_field24', 'form_field25', 'form_field26',
       'form_field27', 'form_field28', 'form_field29', 'form_field30',
       'form_field32', 'form_field33', 'form_field34', 'form_field35',
       'form_field36', 'form_field37', 'form_field38', 'form_field39',
       'form_field42', 'form_field43', 'form_field44', 'form_field46',
       'form_field48', 'form_field49', 'form_field50']

for col in miss_cols:
    data[col] = data[col].fillna(data[col].mean())
    
data.isnull().sum()

form_field1                 0
form_field2                 0
form_field3                 0
form_field4                 0
form_field5                 0
form_field6                 0
form_field7                 0
form_field8                 0
form_field9                 0
form_field10                0
form_field12                0
form_field13                0
form_field14                0
form_field15                0
form_field16                0
form_field17                0
form_field18                0
form_field19                0
form_field20                0
form_field21                0
form_field22                0
form_field24                0
form_field25                0
form_field26                0
form_field27                0
form_field28                0
form_field29                0
form_field30                0
form_field32                0
form_field33                0
form_field34                0
form_field35                0
form_field36                0
form_field37                0
form_field38                0
form_field39                0
form_field42                0
form_field43                0
form_field44                0
form_field46                0
form_field48                0
form_field49                0
form_field50                0
default_status          24000
set                         0
form_field47_charge         0
form_field47_lending        0
dtype: int64

In [46]:
data.describe()

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field42,form_field43,form_field44,form_field46,form_field48,form_field49,form_field50,default_status,form_field47_charge,form_field47_lending
count,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,80000.00000,56000.00000,80000.00000,80000.00000
mean,3491.94217,0.55281,1.05619,0.85413,2.02450,625007.22285,6844769.13172,2634964.11087,13263902.60903,11861530.86201,2771393.59569,6002145.46766,76279711.77059,114397177.94460,0.23158,0.26628,0.27203,0.94570,1.02825,86.68514,6635.78476,104.97275,2625.09795,10107.36554,6193.16031,17406.70445,16515.35224,5223.76055,940.86176,13.99311,0.23009,0.19812,12.83453,8.50272,8.57284,0.09082,0.36866,6.61830,0.56423,0.09614,304133.08282,1.05358,622857.95773,0.24491,0.64800,0.35200
std,184.72485,0.79358,2.15631,3.22313,10.75797,1258424.65715,17447860.60848,3441197.23896,19226240.12718,26050065.20944,4194876.79641,21068876.45452,3068578796.19418,90258598.12732,0.54535,0.63987,0.65002,1.72712,1.77123,45.21890,4524.05904,393.36581,1862.26163,8189.85099,4925.06061,26913.50490,9637.57752,2309.21058,996.85724,15.13191,0.67747,0.43636,10.37785,8.90845,7.90401,0.40316,0.40828,6.34153,0.18694,0.29269,1360017.08227,1.80370,5432270.91414,0.43004,0.47760,0.47760
min,2986.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,539543.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.25500,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.16660,0.00000,0.00000,2.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.04853,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000
25%,3366.00000,0.08005,0.00000,0.00000,0.00000,35010.00000,811843.00000,319758.00000,1831023.00000,452407.00000,404949.00000,295640.00000,16576457.00000,71317315.00000,0.00000,0.00000,0.00000,0.00000,0.00000,60.16125,3734.47500,26.89125,1335.00000,3924.00000,2494.00000,60.00000,9855.00000,5170.00000,226.00000,2.50000,0.00000,0.00000,6.00000,2.00000,4.00000,0.00000,0.00000,2.02000,0.42914,0.00000,192.64434,0.00000,0.06724,0.00000,0.00000,0.00000
50%,3491.94217,0.31243,0.06360,0.00000,0.00000,269966.00000,3329451.00000,2210492.50000,8037518.00000,3752294.00000,1846583.00000,2160506.00000,28141427.00000,114397177.94463,0.00000,0.00000,0.00000,0.00000,0.00000,86.68514,6635.78476,93.64500,2440.50000,9582.00000,6193.16031,486.00000,15147.00000,5223.76055,716.00000,8.16660,0.00000,0.00000,10.00000,8.00000,6.00000,0.00000,0.23913,5.05000,0.56423,0.00000,1773.46674,0.00000,0.28682,0.00000,1.00000,0.00000
75%,3612.00000,0.67920,1.27460,0.00000,0.00000,625007.22285,6844769.13172,2634964.11087,14121283.50000,13135849.25000,2771393.59569,6002145.46766,48187375.00000,114397177.94463,0.23158,0.26628,0.27203,1.00000,1.00000,115.53000,8228.97750,104.97275,3343.50000,12774.00000,7666.00000,60772.00000,21717.00000,6022.00000,1230.00000,21.00000,0.00000,0.19812,16.00000,12.00000,12.00000,0.00000,0.61112,10.10000,0.73995,0.09614,304133.08282,1.17399,1.77674,0.00000,1.00000,1.00000
max,3900.00000,22.31505,57.37160,206.45280,407.74860,53135455.00000,2158794400.00000,113514090.00000,1443921320.00000,2191361480.00000,160923465.00000,2457824146.00000,385498999611.00000,3897066574.00000,11.00000,21.00000,21.00000,28.00000,29.00000,1957.87500,97200.00000,41801.10000,25093.50000,73275.00000,44104.00000,60772.00000,73914.00000,25550.00000,21306.00000,152.00000,21.00000,10.00000,200.00000,120.00000,190.00000,21.00000,2.20000,91.91000,0.80000,19.00000,121399120.00000,28.00000,252459055.32265,1.00000,1.00000,1.00000

There is need to normalize the data so that every variable lies between 0 and 1. In this case, I will use MinMaxScaler from scikit-learn.

In [47]:
# separate the datasets

train_set = data[data['set'] == 'train']
test_set = data[data['set'] == 'test']

test_set.drop(columns = ['default_status', 'set'], axis=1, inplace = True)
train_set.drop(columns = ['set'], axis=1, inplace=True)

X = train_set.drop(columns='default_status', axis=1)
y = train_set['default_status']

In [48]:
# data normalization

from sklearn.preprocessing import MinMaxScaler

normalizer = MinMaxScaler()

train_set = normalizer.fit_transform(X)
test_set = normalizer.fit_transform(test_set)

In [49]:
train_set = pd.DataFrame(train_set)
train_set.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44
count,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000,56000.00000
mean,0.55143,0.03058,0.01834,0.00929,0.00480,0.01175,0.00318,0.02534,0.04116,0.00541,0.02234,0.00244,0.00018,0.03297,0.02097,0.01266,0.01295,0.03389,0.03557,0.04408,0.06822,0.00328,0.10459,0.13793,0.14559,0.28426,0.22348,0.20423,0.04405,0.09064,0.01096,0.01991,0.05484,0.08002,0.05514,0.00433,0.16738,0.07218,0.68523,0.01912,0.00573,0.03747,0.00262,0.64952,0.35048
std,0.20237,0.04398,0.03732,0.03434,0.02570,0.02354,0.00844,0.03303,0.05721,0.01214,0.03324,0.00899,0.00704,0.02584,0.04952,0.03069,0.03117,0.06201,0.06136,0.02312,0.04644,0.01197,0.07437,0.11179,0.11578,0.44174,0.13036,0.09024,0.04658,0.09904,0.03242,0.04396,0.05268,0.08362,0.05092,0.01941,0.18543,0.06905,0.24920,0.05673,0.02452,0.06430,0.02268,0.47713,0.47713
min,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000
25%,0.41319,0.00445,0.00000,0.00000,0.00000,0.00066,0.00038,0.00318,0.00572,0.00021,0.00328,0.00012,0.00004,0.02061,0.00000,0.00000,0.00000,0.00000,0.00000,0.03053,0.03841,0.00085,0.05326,0.05355,0.06011,0.00099,0.13333,0.20235,0.01061,0.01537,0.00000,0.00000,0.02020,0.01887,0.02564,0.00000,0.00000,0.02198,0.50531,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000
50%,0.55158,0.01715,0.00111,0.00000,0.00000,0.00509,0.00154,0.02118,0.02511,0.00172,0.01496,0.00089,0.00007,0.03295,0.00000,0.00000,0.00000,0.00000,0.00000,0.04415,0.06827,0.00293,0.09738,0.13077,0.14565,0.00800,0.20493,0.20445,0.03361,0.05269,0.00000,0.00000,0.04040,0.07547,0.03846,0.00000,0.10869,0.05495,0.68625,0.00000,0.00003,0.00000,0.00000,1.00000,0.00000
75%,0.68132,0.03751,0.02215,0.00000,0.00000,0.01176,0.00317,0.02540,0.04385,0.00600,0.02234,0.00244,0.00013,0.03295,0.02105,0.01268,0.01295,0.03571,0.03448,0.05876,0.08457,0.00329,0.13270,0.17433,0.18028,1.00000,0.29381,0.23569,0.05773,0.13611,0.00000,0.01981,0.07071,0.11321,0.07692,0.00000,0.27778,0.10989,0.91946,0.01923,0.00572,0.04137,0.00000,1.00000,1.00000
max,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000

In [50]:
test_set = pd.DataFrame(test_set)
test_set.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44
count,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000,24000.00000
mean,0.55390,0.02498,0.03084,0.00416,0.00733,0.01299,0.00882,0.02334,0.00933,0.01534,0.01723,0.00431,0.00024,0.02886,0.02596,0.02674,0.02724,0.03910,0.04252,0.10840,0.08317,0.00253,0.13052,0.15281,0.14054,0.29148,0.23526,0.25776,0.08144,0.11288,0.01532,0.02447,0.05673,0.07125,0.04477,0.00605,0.16803,0.07160,0.68104,0.00513,0.00249,0.04434,0.00263,0.64446,0.35554
std,0.20355,0.03570,0.06345,0.01643,0.03821,0.02648,0.02009,0.03061,0.01469,0.03190,0.02707,0.01330,0.00978,0.02375,0.06077,0.06289,0.06392,0.07105,0.07300,0.05651,0.05691,0.01005,0.09210,0.12374,0.11178,0.44544,0.13742,0.11408,0.08668,0.12396,0.04463,0.05358,0.05396,0.07511,0.04110,0.02618,0.18594,0.06887,0.25378,0.01646,0.01220,0.07547,0.02325,0.47869,0.47869
min,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000
25%,0.41357,0.00357,0.00000,0.00000,0.00000,0.00072,0.00104,0.00269,0.00125,0.00056,0.00248,0.00021,0.00004,0.01753,0.00000,0.00000,0.00000,0.00000,0.00000,0.07521,0.04677,0.00064,0.06605,0.05931,0.05655,0.00099,0.13916,0.25445,0.01928,0.01884,0.00000,0.00000,0.02105,0.01667,0.02105,0.00000,0.00000,0.02198,0.49759,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000
50%,0.55355,0.01443,0.00174,0.00000,0.00000,0.00560,0.00435,0.01963,0.00557,0.00480,0.01133,0.00152,0.00007,0.02890,0.00000,0.00000,0.00000,0.00000,0.00000,0.10801,0.08303,0.00226,0.12092,0.14484,0.14042,0.00800,0.21458,0.25710,0.06163,0.06460,0.00000,0.00000,0.04211,0.06667,0.03158,0.00000,0.10869,0.05495,0.67860,0.00000,0.00001,0.00000,0.00000,1.00000,0.00000
75%,0.68709,0.03047,0.03742,0.00000,0.00000,0.01297,0.00888,0.02321,0.00993,0.01692,0.01722,0.00433,0.00013,0.02890,0.02573,0.02663,0.02720,0.04167,0.04167,0.14484,0.10313,0.00251,0.16738,0.19309,0.17518,1.00000,0.31082,0.29343,0.10587,0.16824,0.00000,0.02477,0.07368,0.10000,0.06316,0.00000,0.27810,0.09890,0.92002,0.00506,0.00251,0.05147,0.00000,1.00000,1.00000
max,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000

In [52]:
#Setting up training and validation sets

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression

X_train,X_val,y_train,y_val = train_test_split(X,y,test_size=0.20, random_state=42)

In [53]:
#Print shape for each set
print('X_train: ', X_train.shape)
print('X_val: ', X_val.shape)
print('y_train: ', y_train.shape)
print('y_val: ', y_val.shape)

X_train:  (44800, 45)
X_val:  (11200, 45)
y_train:  (44800,)
y_val:  (11200,)

In [54]:
# save the datasets

X_train.to_csv('X_train.csv', index=False)
X_val.to_csv('X_val.csv', index=False)
y_train.to_csv('y_train.csv', index=False)
y_val.to_csv('y_val.csv', index=False)